### ISSUE TITLE
Import play list - Error: invalid XML format.

### ISSUE THREAD

**Issue by msanecki** [stu247/spl#4] opened 2016-11-20 19:30 UTC
Hi there,

there is one play list stored on my sonos system. After execution of spl.py -X 
one file was created:

Here is the content.
<?xml version="1.0" encoding="UTF-8"?>
<playlist version="1" xmlns="http://xspf.org/ns/0/">
 <title>Worship</title>
 <trackList>
  <track>
   <creator>Brian and Jenn Johnson</creator>
   <title>Where You Go I Go</title>
   <album>Where You Go I Go: Live From Bethel Church In Redding, CA</album>
   <location>x-sonosapi-hls-static:library%2fplaylists%2f19f24ce3-7f43-4c41-8db6-718bbff4c9b3%2f2494fe09-4bbe-4ce2-8c1a-b4f2d9c9d10c%2f?sid=201&flags=8224&sn=2</location>
  </track>
 </trackList>
</playlist>

Then I removed the play list from the sonos system and wanted to check if the local stored file will be imported

C:\Users\User\Downloads\spl>dir
 Volume in Laufwerk C: hat keine Bezeichnung.
 Volumeseriennummer: 76AA-47A2

 Verzeichnis von C:\Users\User\Downloads\spl

20.11.2016  20:12    <DIR>          .
20.11.2016  20:12    <DIR>          ..
16.11.2016  23:33            18.698 spl.py
20.11.2016  20:12               504 Worship.xspf
               2 Datei(en),         19.202 Bytes
               2 Verzeichnis(se), 412.961.488.896 Bytes frei

C:\Users\User\Downloads\spl>spl.py -i Worship.xspf
**Error: invalid XML format.**

**Comment by stu247** [comment] 2016-11-20 20:36
Could you please attach Worship.xspf to a comment so I can see it without formatting?

**Comment by msanecki** [comment] 2016-11-20 20:50
I thinkit is because of the <location> content, there are the two '&'. I checked it and the import works when ther is &amp; istead of  '&'.

After import the list appears in the controller but seems to be empty, no tracks are listed it's not possible to play the list.

[Worship.txt](https://github.com/stu247/spl/files/602309/Worship.txt)

I was to quick. I have experimented a little bit and the thing is that the list can be imported (&amp; istead of '&') the tracks are there and can be played but the tracks names are empty.

**Comment by stu247** [comment] 2016-11-20 22:41
I have pushed a fix (https://github.com/stu247/spl/commit/4d8786b43c12a53f64241e1e611a32b5bf4ad8d8).  I could not reproduce the issue, so I could not validate the fix.  Please try the new version and let me know if it works.

**Comment by msanecki** [comment] 2016-11-21 06:43
Here is my result:
C:\Users\User\Downloads\spl\fix>spl.py -V -X
Traceback (most recent call last):
  File "C:\Users\User\Downloads\spl\fix\spl.py", line 489, in <module>
    spl = SPL()
  File "C:\Users\User\Downloads\spl\fix\spl.py", line 426, in __init__
    self.exportPl(speaker, pl, args.force, args.exportDetails)
  File "C:\Users\User\Downloads\spl\fix\spl.py", line 127, in exportPl
    max_items=max_items)
  File "build\bdist.win32\egg\soco\music_library.py", line 346, in browse
  File "build\bdist.win32\egg\soco\data_structures.py", line 99, in from_didl_string
  File "build\bdist.win32\egg\soco\data_structures.py", line 513, in from_element
  File "build\bdist.win32\egg\soco\utils.py", line 43, in really_unicode
ValueError: None is not a string at all.

Thanks,
Marcin

**Comment by stu247** [comment] 2016-11-21 23:14
1. I am not sure what to make of your error message.  I can only get line 127 to execute if I have installed SoCo 0.12, but in that case I must use the -I option as a work around, but you did not.  What version of SoCo are you running?  You can find this by running python and then enter
\>>> import soco
\>>> print(soco.\_\_version\_\_)
\>>> exit()

2. Are you trying to export the same playlist as last time?  The track was type "x-sonosapi-hls-static".  I have not seen that type before.  I only use type "x-file-cifs", which is Samba file system path.  Do you know what is type "x-sonosapi-hls-static"?

**Comment by msanecki** [comment] 2016-11-22 07:36
Ad. 1.
Because of "General problem by execution #3" I moved from SoCo 0.12 to 0.11.1(as it was suggested by SoCo devs) to be able to execute the spl.py script at all. 
All test are performed based on SoCo 0.11.1 and python 2.7.12

Ad.2. No idea about the sonos types but I will check it on the evening an let you know.

**Comment by stu247** [comment] 2016-11-22 19:04
I think your installation of SoCo is messed up.  The backtrace says you executed code in soco\music_library.py, but that file only exists in version 0.12.  Maybe you have files from both versions?  Try uninstalling all of the SoCo files and reinstall.

**Comment by msanecki** [comment] 2016-11-23 21:46
I got the problem because I have added some new tracks to the list and that was why the file couldn't be imported.
I am not going to create a new issue for that right now. I will test it once again later.

So now I have created a test list on my controller and exported it successfully. 
```
C:\Users\User\Downloads\spl\fix>spl.py -X
Test: 1 songs
```
Here is the content:
[Testlist-after-export.txt](https://github.com/stu247/spl/files/610050/Testlist-after-export.txt)

Then I deleted the list on the controller and tried to import the exported one:
```
C:\Users\User\Downloads\spl\fix>spl.py -i Testlist-after-export.xspf
.
```
The imported list appears on the controller the one track is listed but without name and it cannot be played.

Then I tried to export this list again:

```
C:\Users\User\Downloads\spl\fix>spl.py -X
Traceback (most recent call last):
  File "C:\Users\User\Downloads\spl\fix\spl.py", line 489, in <module>
    spl = SPL()
  File "C:\Users\User\Downloads\spl\fix\spl.py", line 426, in __init__
    self.exportPl(speaker, pl, args.force, args.exportDetails)
  File "C:\Users\User\Downloads\spl\fix\spl.py", line 127, in exportPl
    max_items=max_items)
  File "build\bdist.win32\egg\soco\music_library.py", line 346, in browse
  File "build\bdist.win32\egg\soco\data_structures.py", line 99, in from_didl_string
  File "build\bdist.win32\egg\soco\data_structures.py", line 513, in from_element
  File "build\bdist.win32\egg\soco\utils.py", line 43, in really_unicode
ValueError: None is not a string at all.
```
Here is the exported file:
[Test.txt](https://github.com/stu247/spl/files/610078/Test.txt)

I have also tried to export the list using the master branch version of spl.py

```
C:\Users\User\Downloads\spl>spl.py -X
C:\Users\User\Downloads\spl\spl.py:114: UserWarning: Call to deprecated function browse. Will be removed in version 0.14. Use soco.music_library.browse instead.
  max_items=max_items)
Test: 1 songs
```
The only diff is the '&' vs `"&amp;" `in the fix branch version.

BTW I looked into the soco-0.11.1-py2.7.egg and the file soco\music_library.py is there.

**Comment by stu247** [comment] 2016-11-24 15:13
For item 1, if you use the command `pip install soco==0.11.1`, it will install the wheel at (https://pypi.python.org/pypi/soco/0.11.1#downloads), this wheel does not have the file soco/music_library.py  What is the URL to the egg you used?

For item 2, I would like to recreate your scenario as best as possible.  Could you please explain the steps involved in creating your track?  It appears to be a URL instead of a path to an MP3 file.  For example, I have a bunch of of MP3 files on a computer.  I went into settings on Sonos app and selected Manage Music Library and then selected Music Library Setup.  There I added a Share for the computer with the MP3 files.  This causes all of my MP3 songs to appear in the Music Library.  I then added specific tracks in the Music Library to the playlist.  Is your track in the playlist from your Music Library?  If so, how was the Music Library created?

**Comment by msanecki** [comment] 2016-11-24 19:59
Ad 1.
Regarding the version soco 0.11.1 I have to say it is a bit strange for me now. I have downloaded the sources from soco github master branch and in the source directory executed the command "setup.py install" as suggested hier: https://github.com/SoCo/SoCo/issues/449#issuecomment-261786380

After that the version 0.11.1 was installed. What I don't understand is that the latest release version is 0.12. and  the master branch version is labeled 0.11.1.

Ad 2.
My playlists consists of tracks from amazon music. When I listen to some station/category I add the songs I like to my sonos playlist.
Generally if you use few streaming services you are able to create a list from resources from different providers. It is possiblt not ony to add a single track but also a whol category (with many track).
Creating a Sonos playlist I am able to mix resources from many services in one place what is very useful for me.

**Closed as completed** 2019-05-26 20:28 UTC
